disabled_rules:
  - todo

excluded:
  - .build
  - DerivedData

trailing_comma:
  mandatory_comma: true

line_length:
  warning: 160
  error: 240

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - i
    - j
    - k
